### ISSUE TITLE
Build looks for cppunit when tests aren't built

### ISSUE THREAD

**Issue by yurivict** [Martchus/tagparser#26]

**Comment by Martchus** [comment]
That's correct but you will get away with the warning `Unable to add test target because cppunit could not be located.`. So this should be fine. The problem is that at configuration time the build system doesn't know whether the target for tests is going to be invoked or not so it just needs to look for cppunit to make sure the target is available if possible. Maybe I can add an option to disable the lookup but generally it shouldn't be required.

**Comment by yurivict** [comment]
Lookup for cppunit should be only enabled when the tests tests are built or run. This should be based on the ```BUILD_TESTING``` cmake variable.

**Comment by Martchus** [comment]
Implemented via https://github.com/Martchus/cpp-utilities/commit/938da48da0dcea292ff970ba38a512e295258425.
