### ISSUE TITLE
In abstracttrack.h, duration() cannot detect the length of tracks in matroska containers; outputs default TimeSpan of zero ticks

### ISSUE THREAD

**Issue by SentToDevNull** [Martchus/tagparser#5]
This is the case for all audio, video, and subtitle tracks in the MKV files I've tested.

**Comment by Martchus** [comment]
Duration of Matroska files is set on Segment-level and not on Track-level. Hence the property is only available via `AbstractContainer`.

For formats which specify the duration on track-level, `AbstractContainer::duration()` will return the duration of the longest track. I could implement it to work the other way around, too. So the track will return the duration from the container if no duration is available at track-level. I haven't implemented that because I don't need it.

So do you still need that feature knowing that you can use `AbstractContainer::duration()` instead?

**Comment by Martchus** [comment]
Note that the library is now able to read [track-specific meta data written by mkvmerge](https://github.com/mbunkus/mkvtoolnix/wiki/Automatic-tag-generation).

If such meta-data is not available, a fallback to `AbstractContainer::duration()` might still make sense.

**Comment by Martchus** [comment]
Likely not very important and an automatic fallback (on the level of this library) is also questionable.
