### ISSUE TITLE
Playstation3 cannot play mp4 files edited the tags

### ISSUE THREAD

**Issue by ponsfoot** [Martchus/tagparser#7]
After editing tags of mp4 files, Playstation3 recognizes those files are broken (unplayable).
ffmpeg -i shows the following message:
`[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56489a625520] overread end of atom 'tkhd' by 4 bytes`

Versions:
tageditor 2.2.5
tagparser 6.4.0
c++utilities 4.9.2
on ArchLinux(x86_64)

On tageditor2.2.3 and tagparser6.3.0, this issue doesn't occur.

[ffmpeg_i.txt](https://github.com/Martchus/tagparser/files/1298406/ffmpeg_i.txt)

**Comment by Martchus** [comment]
Ok, I'll look into it. Does it happen with all MP4 files (what was the muxing application)? How did you edit the file exactly (eg. CLI command)?

**Comment by ponsfoot** [comment]
> Does it happen with all MP4 files

Yes. ffmpeg and playstation3 shows the warning/error message for all edited MP4 files.

> what was the muxing application or the particular files you can reproduce the issue with?

handbrake 1.0.7 and Lavf52.64.0 (sample_h264.mp4 for this test)

> How did you edit the file exactly (eg. CLI command)?

Both GUI and CLI. I edited only title to "test" to confirm this issue.

Regards

**Comment by ponsfoot** [comment]
P.S.
This issue doesn't affect to play with mpv and vlc on my system (only shown ffmpeg warning messages on mpv).

**Comment by Martchus** [comment]
The issue occurred when I added a new feature to the library which allows to set track-related metadata (language, name, ...).

It should be fixed with https://github.com/Martchus/tagparser/commit/ba8c9204a9aeaafa87f58cbebd3286657d3de23b.

> This issue doesn't affect to play with mpv and vlc on my system

That's the reason why I didn't discovered the issue when testing. But the files are damaged, though.

To restore the damaged files, you can simply remux with ffmpeg: `ffmpeg -i damaged.mp4 -c copy repaired.mp4`  
This will not re-encode anything (and hence not cause quality loss). At least the warning in ffmpeg is then gone (not sure about PS3).

I'll release a fixed version including the mentioned commit soon.

**Comment by ponsfoot** [comment]
Confirmed that this issue is fixed on PS3 as well.
Thx
